[project]
name = "shapefm-gift-eval-environment"
version = "0.1.0"
requires-python = ">=3.12,<3.13"
dependencies = [
  "salesforce-gift-eval",
]

[tool.uv]
required-version = "==0.12.18"
package = false
environments = [
  "sys_platform == 'darwin' and platform_machine == 'arm64'",
  "sys_platform == 'linux' and platform_machine == 'x86_64'",
]

[tool.uv.sources]
salesforce-gift-eval = { path = "../../external/gift-eval" }
